## Basic Configuration

baseurl = "https://davemartorana.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Dave Martorana"
title = "This is Dave Martorana"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "discusShortname" # Enable if you want to use Disqus
googleAnalytics = "G-W658Y29393" # Enable if you want to use Google Analytics
enableRobotsTXT = true

## Site Settings
[params]
author = "This is Dave Martorana"
intro = "Father, husband. Entrepreneur. Software engineer. Musician."
description = """
May, 1978 - ?

Co-owner, {{< link title="Flyclops LLC" url="https://flyclops.com" target="_blank" >}}
"""
authorimage = "headshot.png"
dateformat = "2006-01-02"

## Site Meta Settings
[params.meta]
description = "This is Dave Martorana"
keywords = "martorana,dave,developer,blog,hugo,software,engineer,flyclops"

## Social Accounts
[params.social]
github = "themartorana"
instagram = "davemartorana"
linkedin = "davidmartorana"
bluesky = "dave.am"

## Extras
[params.extra]
copyright = "© 2025. Dave Martorana. All Rights Reserved"
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
name = "about dave"
identifier = "about"
weight = 100
url = "/about/"

[[menu.main]]
name = "flyclops"
identifier = "flyclops"
weight = 200
url = "https://flyclops.com"

[[menu.main]]
name = "sean martorana"
identifier = "sean-martorana"
weight = 300
url = "https://seanmartorana.com"

[[menu.main]]
name = "ivi"
identifier = "ivi"
weight = 400
url = "https://ivilife.com"
class = "rainbow-text"